DROP TABLE IF EXISTS `bb_fuzhaibiao`;
CREATE TABLE `bb_fuzhaibiao` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `A` VARCHAR(100) DEFAULT NULL COMMENT '地区',
  `B` VARCHAR(100) DEFAULT NULL COMMENT '清查单位',
  `C` VARCHAR(100) DEFAULT NULL COMMENT '资产总计账面数',
  /* D */
  `D` VARCHAR(100) DEFAULT NULL COMMENT '资产总计核实数',
  `E` VARCHAR(100) DEFAULT NULL COMMENT '流动资产合计 账面数',
  /* F */
  `F` VARCHAR(100) DEFAULT NULL COMMENT '流动资产合计 核实数',
  `G` VARCHAR(100) DEFAULT NULL COMMENT '货币资金 账面数',
  /* H */
  `H` VARCHAR(100) DEFAULT NULL COMMENT '货币资金 核实数',
  `I` VARCHAR(100) DEFAULT NULL COMMENT '短期投资 账面数',
  `J` VARCHAR(100) DEFAULT NULL COMMENT '短期投资 核实数',
  `K` VARCHAR(100) DEFAULT NULL COMMENT '应收款项 账面数',
  /* L */
  `L` VARCHAR(100) DEFAULT NULL COMMENT '应收款项 核实数',
  `M` VARCHAR(100) DEFAULT NULL COMMENT '存款 账面数',
  `N` VARCHAR(100) DEFAULT NULL COMMENT '存款 核实数',
  `O` VARCHAR(100) DEFAULT NULL COMMENT '农业资产合计 账面数',
  `P` VARCHAR(100) DEFAULT NULL COMMENT '农业资产合计 核实数',
  `Q` VARCHAR(100) DEFAULT NULL COMMENT '牲畜资产 账面数',
  `R` VARCHAR(100) DEFAULT NULL COMMENT '牲畜资产 核实数',
  `S` VARCHAR(100) DEFAULT NULL COMMENT '林木资产 账面数',
  `T` VARCHAR(100) DEFAULT NULL COMMENT '林木资产 核实数',
  `U` VARCHAR(100) DEFAULT NULL COMMENT '长期资产合计 账面数',
  /* V */
  `V` VARCHAR(100) DEFAULT NULL COMMENT '长期资产合计 核实数',
  `W` VARCHAR(100) DEFAULT NULL COMMENT '长期投资 账面数',
  /* X */
  `X` VARCHAR(100) DEFAULT NULL COMMENT '长期投资 核实数',
  `Y` VARCHAR(100) DEFAULT NULL COMMENT '长期股权投资 账面数',
  /* Z */
  `Z` VARCHAR(100) DEFAULT NULL COMMENT '长期股权投资 核实数',
  `AA` VARCHAR(100) DEFAULT NULL COMMENT '固定资产合计 账面数',
  /* AB */
  `AB` VARCHAR(100) DEFAULT NULL COMMENT '固定资产合计 核实数',
  `AC` VARCHAR(100) DEFAULT NULL COMMENT '固定资产原值 账面数',
  /* AD */
  `AD` VARCHAR(100) DEFAULT NULL COMMENT '固定资产原值 核实数',
  `AE` VARCHAR(100) DEFAULT NULL COMMENT '累计折扣 账面数',
  `AF` VARCHAR(100) DEFAULT NULL COMMENT '累计折扣 核实数',
  `AG` VARCHAR(100) DEFAULT NULL COMMENT '固定资产净值 账面数',
  /* AH */
  `AH` VARCHAR(100) DEFAULT NULL COMMENT '固定资产净值 核实数',
  `AI` VARCHAR(100) DEFAULT NULL COMMENT '经营性固定资产 账面数',
  `AJ` VARCHAR(100) DEFAULT NULL COMMENT '经营性固定资产 核实数',
  `AK` VARCHAR(100) DEFAULT NULL COMMENT '固定资产清理 账面数',
  /* AL */
  `AL` VARCHAR(100) DEFAULT NULL COMMENT '固定资产清理 核实数',
  `AM` VARCHAR(100) DEFAULT NULL COMMENT '在建工程 账面数',
  /* AN */
  `AN` VARCHAR(100) DEFAULT NULL COMMENT '在建工程 核实数',
  `AO` VARCHAR(100) DEFAULT NULL COMMENT '经营性在建工程 账面数',
  `AP` VARCHAR(100) DEFAULT NULL COMMENT '经营性在建工程 核实数',
  `AQ` VARCHAR(100) DEFAULT NULL COMMENT '其他资产 账面数',
  `AR` VARCHAR(100) DEFAULT NULL COMMENT '其他资产 核实数',
  `AS` VARCHAR(100) DEFAULT NULL COMMENT '无形资产 账面数',

  `AT` VARCHAR(100) DEFAULT NULL COMMENT '无形资产 核实数',
  `AU` VARCHAR(100) DEFAULT NULL COMMENT '负债和所有者权益 账面数',
  `AV` VARCHAR(100) DEFAULT NULL COMMENT '负债和所有者权益 核实数',
  `AW` VARCHAR(100) DEFAULT NULL COMMENT '流动负债合计 账面数',
  /* AX */
  `AX` VARCHAR(100) DEFAULT NULL COMMENT '流动负债合计 核实数',
  `AY` VARCHAR(100) DEFAULT NULL COMMENT '短期借款 账面数',
  /* AZ */
  `AZ` VARCHAR(100) DEFAULT NULL COMMENT '短期借款 核实数',
  `BA` VARCHAR(100) DEFAULT NULL COMMENT '应付款项 账面数',
  /* BB */
  `BB` VARCHAR(100) DEFAULT NULL COMMENT '应付款项 核实数',
  `BC` VARCHAR(100) DEFAULT NULL COMMENT '应付工资 账面数',
  /* BD */
  `BD` VARCHAR(100) DEFAULT NULL COMMENT '应付工资 核实数',
  `BE` VARCHAR(100) DEFAULT NULL COMMENT '应付福利费 账面数',
  /* BF */
  `BF` VARCHAR(100) DEFAULT NULL COMMENT '应付福利费 核实数',
  `BG` VARCHAR(100) DEFAULT NULL COMMENT '长期负债合计 账面数',
  /* BH */
  `BH` VARCHAR(100) DEFAULT NULL COMMENT '长期负债合计 核实数',
  `BI` VARCHAR(100) DEFAULT NULL COMMENT '长期借款及应付款 账面数',
  /* BJ */
  `BJ` VARCHAR(100) DEFAULT NULL COMMENT '长期借款及应付款 核实数',
  `BK` VARCHAR(100) DEFAULT NULL COMMENT '一事一议资金 账面数',
  /* BL */
  `BL` VARCHAR(100) DEFAULT NULL COMMENT '一事一议资金 核实数',
  `BM` VARCHAR(100) DEFAULT NULL COMMENT '专项应付款 账面数',
  /* BN */
  `BN` VARCHAR(100) DEFAULT NULL COMMENT '专项应付款 核实数',
  `BO` VARCHAR(100) DEFAULT NULL COMMENT '征地补偿费 账面数',
  /* BP */
  `BP` VARCHAR(100) DEFAULT NULL COMMENT '征地补偿费 核实数',
  `BQ` VARCHAR(100) DEFAULT NULL COMMENT '合计 账面数',
  `BR` VARCHAR(100) DEFAULT NULL COMMENT '合计 核实数',
  `BS` VARCHAR(100) DEFAULT NULL COMMENT '资本 账面数',
  `BT` VARCHAR(100) DEFAULT NULL COMMENT '资本 核实数',
  `BU` VARCHAR(100) DEFAULT NULL COMMENT '政府拨款等形式 账面数',
  /* BV */
  `BV` VARCHAR(100) DEFAULT NULL COMMENT '政府拨款等形式 核实数',
  `BW` VARCHAR(100) DEFAULT NULL COMMENT '公益公积金 账面数',
  `BX` VARCHAR(100) DEFAULT NULL COMMENT '公益公积金 核实数',
  `BY` VARCHAR(100) DEFAULT NULL COMMENT '征地补偿转入 账面数',
  `BZ` VARCHAR(100) DEFAULT NULL COMMENT '征地补偿转入 核实数',
  `CA` VARCHAR(100) DEFAULT NULL COMMENT '未分配收益 账面数',
  `CB` VARCHAR(100) DEFAULT NULL COMMENT '未分配收益 核实数',
  `CC` VARCHAR(100) DEFAULT NULL COMMENT '经营性资产 账面数',
  `CD` VARCHAR(100) DEFAULT NULL COMMENT '经营性资产 核实数',
  `CE` VARCHAR(100) DEFAULT NULL COMMENT '非经营性资产 账面数',
  /* CF */
  `CF` VARCHAR(100) DEFAULT NULL COMMENT '非经营性资产 核实数',
  `CG` VARCHAR(100) DEFAULT NULL COMMENT '待界定资产 账面数',
  `CH` VARCHAR(100) DEFAULT NULL COMMENT '待界定资产 核实数',
  `CI` VARCHAR(100) DEFAULT NULL COMMENT '全资子公司所有者权益 账面数',
  `CJ` VARCHAR(100) DEFAULT NULL COMMENT '全资子公司所有者权益 核实数',

  PRIMARY KEY (`Id`)
) ENGINE=MyISAM AUTO_INCREMENT=2241 DEFAULT CHARSET=utf8 COMMENT='资产负债表(组织)信息';